name = "JuliaRegistry"
uuid = "6cc4543a-1e63-4f50-814a-2024cd655bdd"
repo = "git@github.com:grasph/GrasphRegistry.git"
description = "Philippe's Julia registry"

[packages]
45b42145-bbac-5752-8807-01f8b2702242 = { name = "ROOT_jll", path = "jll/R/ROOT_jll" }
